### ISSUE TITLE
Option to subscribe to chain rollbacks

### ISSUE THREAD

**Issue by mdcryptonfts** [eosswedenorg/thalos#30]
Hi, from my understanding, a ship node should send out a message to the node(s) reading from it, and let them know if the chain has had a fork/rollback.

If possible, it would be nice to be able to subscribe to this message using thalos/redis.

This way, an app running thalos could cache any actions/transactions that it indexes for x_minutes, and then if a message comes in on ship::chain::rollback, it can take the block_num from the rollback message, and reverse any indexing that took place on/after that block.

If not possible, Thalos can still be run in irreversible_only, and a ship can also be run that way, so there are workarounds to keep data reliable.

But a rollback channel would still be beneficial for services wanting to provide real time data on a front end, for example displaying NFTs or token balances.

**Comment by pnx** [comment]
Hi! Thanks for the feedback :) this will certainly be nice to have. I will look into it!

**Comment by pnx** [comment]
I found this: https://github.com/blockmatic/antelope-ship-reader/blob/master/src/index.ts#L383

And implemented it in: https://github.com/eosswedenorg/thalos/tree/rollback

I will run the new code for a while. but if you want/can you can compile the branch and test yourself :) will be much appreciated!

**Comment by pnx** [comment]
Adding in version 0.3.0
